name: doctor_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0

  # ----------------------------
  # State Management
  # ----------------------------
  provider: ^6.1.5

  # ----------------------------
  # Networking
  # ----------------------------
  dio: ^5.9.0
  http: ^1.6.0

  # ----------------------------
  # Routing
  # ----------------------------
  go_router: ^17.3.0
  url_launcher: ^6.3.1

  # ----------------------------
  # Local Storage
  # ----------------------------
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.5

  # ----------------------------
  # Authentication
  # ----------------------------
  local_auth: ^2.3.0

  # ----------------------------
  # Firebase
  # ----------------------------
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0

  # ----------------------------
  # Media
  # ----------------------------
  video_player: ^2.9.5

  # ----------------------------
  # PDF
  # ----------------------------
  pdf: ^3.11.3
  printing: ^5.14.2

  # ----------------------------
  # Utilities
  # ----------------------------
  intl: ^0.20.2

  # ----------------------------
  # UI
  # ----------------------------
  flutter_svg: ^2.2.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  record: ^7.1.1
  path_provider: ^2.1.6
  just_audio: ^0.10.6
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/privacy/
    - assets/images/profile/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/vena_app_icon.png"

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/vena_app_icon.png"

  remove_alpha_ios: true